language: python
python:
  - "2.7"
install: 
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script: 
  - ./manage.py check
  - coverage run --source=. ./manage.py test
after_success:
  - codecov
sudo: false

